### ISSUE TITLE
failure to unzip

### ISSUE THREAD

**Issue by chenyang1999** [owkin/HE2RNA_code#1]
I want to unzip tile_coordinates.gz, but it's not a *.gz file, but it looks like a lfs file pointer, so how can I download the real file?
I hava try to use `git lfs clone clone  https://github.com/owkin/HE2RNA_code.git`
but,
```
(.env) hx@hx-b412:~/data/cy/thusz$ git lfs clone https://github.com/owkin/HE2RNA_code.git
Cloning into 'HE2RNA_code'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 72 (delta 7), reused 72 (delta 7), pack-reused 0
Unpacking objects: 100% (72/72), done.
Checking connectivity... done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/owkin/HE2RNA_code.git/info/lfs'
```
Thank your hard work a lot, please excuse my poor English.

**Comment by leandrofmoreno** [comment]
You can download the file manually. It will work.

**Comment by crisz** [comment]
@leandrofmoreno where is the file?

**Comment by benoitschmauch** [comment]
Hi,
Sorry for this problem. Coordinates of tiles used throughout the paper can be downloaded directly from https://drive.google.com/file/d/1PJsUv1SQieJs7hqtWOqW68v1K9c-mIF6/view?usp=sharing.
Best,

Benoît
